### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by circa10a**
For #6 
As of now, Travis tests are failing due to image problems.

### CODE REVIEW

**Comment by gmemstr** [comment]
will take a look at this when I get home in about 30 minutes. thanks!

**Comment by gmemstr** [comment]
Merged into docker branch for review, please use that branch for docker support for the time being

**Comment by circa10a** [comment]
You don't want to use `docker ps -a` in your travis.yml file. The -a flag shows all containers. In the event there is an issue with your docker image, the container wouldn't start, meaning tests have failed, but your container would still exist and would be found by grep, falsifying your tests that the docker image is good.

In short, need to change docker ps -a to docker ps

**Comment by gmemstr** [comment]
@circa10a Staring at your comment I've actually figured out why the image wasn't starting properly. Thanks for pointing that out! :p

**Pull request merged**
