### PR TITLE
Added Cookie based sessions, Refactored and added Login Page

### PR DESCRIPTION
**Pull request by ishanjain28**
I have made quite a few changes in these commits. 

1. Added a login page where users can enter their credentials. If the credentials are correct, An encrypted cookie is sent with the request. 
2. Refactored the code. I created several packages like `auth` where for session creation and verification code, `admin` for the operations that only an authorised user or admin can perform, `router` for all the http router code. 
3. Updated Makefile.

The current structure is reusable and most functions can be used with any other feature you wish to add. 

If there is any thing that looks confusing, feel free to tell me about it and I'll try my best to explain it..

### CODE REVIEW

**Comment by ishanjain28** [comment]
I see you were using govendor for dependency management, AFAIK, You do not need to put the `vendor/github.com` and `vendor/golang.org` folders to git because running `govendor sync` reads `vendor.json` and pulls the correct dependencies. So, I removed those folders and added vendor.json. 


Also, Since I was working on my fork, All the imports are `github.com/ishanjain28/*` which is not correct, Can you change those imports and put your github username there?

**Comment by ishanjain28** [comment]
I see you were using govendor for dependency management, AFAIK, You do not need to put the `vendor/github.com` and `vendor/golang.org` folders to git because running `govendor sync` reads `vendor.json` and pulls the correct dependencies. So, I removed those folders and added vendor.json. 


Also, Since I was working on my fork, All the imports are `github.com/ishanjain28/*` which is not correct, Can you change those imports and put your github username there?

Edit: I Re-added deps in vendor folder because travis was failing. A solution to this would be either edit makefile, So it would first download the deps and then build the project or simply remove Makefile.

**Comment by gmemstr** [comment]
Merging into auth-refac so I can really learn the new changes before merging into master, thank you!

**Comment by gmemstr** [comment]
Merged

**Pull request merged**
